# Use the official Mongo image as the base
FROM mongo:7.0.5

# Update the package list
RUN apt-get update

# Install MongoDB Shell (mongosh)
RUN apt-get install -y mongodb-mongosh

# Copy wait-for-it.sh
WORKDIR /app
COPY startup-scripts/wait-for-it.sh .
RUN chmod +x *.sh