# Use this has a base image. This already has NPM adn Node.js
FROM node:20.11.0

WORKDIR /app
COPY startup-scripts/wait-for-it.sh .
RUN chmod +x *.sh

# Copy package.json file and install dependencies listed
COPY react-app/package.json .
RUN npm install

# Copy rest of the the react-app
COPY react-app .

# Build the react app
RUN npm run build

# Create this path if it does not exist. This path will be mounted to a volume
RUN mkdir -p /usr/share/nginx/html

CMD ["tail", "-f", "/dev/null"]
