# Use the official Nginx image as the base image
FROM nginx:alpine

# Install openssl for generating self-signed certificate and bash
RUN apk add --no-cache openssl bash

# Create the directory for SSL certificates
RUN mkdir -p /etc/nginx/ssl/

# Expose port 80 to the Docker host
EXPOSE 80 443

# Copy wait-for-it.sh to check if services are up
WORKDIR /app
COPY startup-scripts/wait-for-it.sh .
RUN chmod +x *.sh