version: '3.8'

services:
  nginx-service:
    build:
      context: .
      dockerfile: ./nginx-service/Dockerfile
    image: img-nginx-service:latest
    container_name: nginx-service
    volumes:
      - nginx_volume:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    restart: always
  mariadb-service:
    build:
      context: .
      dockerfile: ./mariadb-service/Dockerfile
    image: img-mariadb-service:latest
    container_name: mariadb-service
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always
    environment: {'MYSQL_ROOT_PASSWORD': 'tracetech', 'MYSQL_DATABASE': 'tracetech_db'}
  mongodb-service:
    build:
      context: .
      dockerfile: ./mongodb-service/Dockerfile
    image: img-mongodb-service:latest
    container_name: mongodb-service
    volumes:
      - mongodb_volume:/data/db
    restart: always
    environment: {'MONGO_INITDB_ROOT_USERNAME': 'root', 'MONGO_INITDB_ROOT_PASSWORD': 'tracetech', 'MONGO_INITDB_AUTH_SOURCE': 'admin', 'MONGO_INITDB_DATABASE': 'tracetech_db'}
    command: mongod --auth
  authentication-service:
    build:
      context: .
      dockerfile: ./authentication_service/Dockerfile
    image: img-authentication-service:latest
    container_name: authentication-service
    depends_on:
      - mariadb-service
      - mongodb-service
    restart: always
    environment: {'DOMAIN_NAME': 'www.tracetech.com', 'JWT_SECRET_KEY': 'dc004b2a-005f-4311-b4bd-909c7b108d47', 'MARIADB_DATABASE_URL': 'mysql://root:tracetech@mariadb-service:3306/tracetech_db', 'DEFAULT_APPLICATION_USERNAME': 'admin@tracetech.com', 'DEFAULT_APPLICATION_PASSWORD': 'admin123A!!', 'DEFAULT_APPLICATION_EMAIL': 'admin@tracetech.com'}
  license-service:
    build:
      context: .
      dockerfile: ./license_service/Dockerfile
    image: img-license-service:latest
    container_name: license-service
    depends_on:
      - authentication-service
    restart: always
    environment: {'DOMAIN_NAME': 'www.tracetech.com', 'JWT_SECRET_KEY': 'dc004b2a-005f-4311-b4bd-909c7b108d47', 'MARIADB_DATABASE_URL': 'mysql://root:tracetech@mariadb-service:3306/tracetech_db', 'MONGODB_DATABASE_URL': 'mongodb://root:tracetech@mongodb-service:27017/tracetech_db?authSource=admin', 'MONGODB_DB_NAME': 'tracetech_db', 'LICENSE_KEY': 'ewogInVzZXJzIjogMTAsCiAiZXhwaXJ5X29uIjogIjAxLTAxLTIxMDAiCn0="'}

volumes:
  nginx_volume:
    name: nginx_volume
  mariadb_volume:
    name: mariadb_volume
  mongodb_volume:
    name: mongodb_volume