# Generated by Django 5.0.2 on 2024-02-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensekey', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
