# Generated by Django 5.0.2 on 2024-02-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='license',
            table='license',
        ),
    ]
